---
version: '3'
services:
  ffmpeg:
    build: .
    container_name: ffmpeg
    env_file:
      - ./work.env
    working_dir: /tmp
    volumes:
      - ./files:/tmp/files
      - ./scripts:/tmp/scripts
    tty: true
    # entrypoint: ${ENTRYPOINT:-/tmp/scripts/exau.sh}
